version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: npm start

  webpack:
    # container_name: webpack
    build: .
    depends_on:
      - web
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: webpack --watch
